packages:
  - apps/react/*
  - apps/vue/*
  - packages/*
  - '!**/test/**'

overrides:
  chokidar: 3.5.3
catalogs:
  default:
    '@changesets/changelog-github': ^0.5.2
    '@changesets/cli': ^2.29.8
    '@commitlint/cli': ^20.2.0
    '@emotion/css': ^11.13.5
    '@icebreakers/commitlint-config': ^1.2.3
    '@icebreakers/eslint-config': ^1.6.6
    '@icebreakers/monorepo': ^3.1.8
    '@icebreakers/stylelint-config': ^1.2.3
    '@stylexjs/babel-plugin': ^0.7.3
    '@stylexjs/stylex': ^0.7.3
    '@types/fs-extra': ^11.0.4
    '@types/node': ^25.0.1
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    '@types/semver': ^7.7.1
    '@vanilla-extract/css': ^1.15.3
    '@vanilla-extract/vite-plugin': ^4.0.10
    '@vitejs/plugin-react': ^5.1.2
    '@vitejs/plugin-vue': ^6.0.3
    '@vitest/coverage-v8': ~4.0.15
    ci-info: ^4.3.1
    class-variance-authority: ^0.7.1
    cross-env: ^10.1.0
    defu: ^6.1.4
    es-toolkit: ^1.43.0
    eslint: ^9.39.2
    execa: ^9.6.1
    fs-extra: ^11.3.2
    husky: ^9.1.7
    lint-staged: ^16.2.7
    only-allow: ^1.2.2
    pathe: ^2.0.3
    pkg-types: ^2.3.0
    react: ^19.0.0
    react-dom: ^19.0.0
    rimraf: ^6.1.2
    sass: ^1.96.0
    styled-components: ^6.1.13
    styled-jsx: ^5.1.3
    stylelint: ^16.26.1
    tsdown: 0.17.3
    tslib: ^2.8.1
    tsup: ^8.5.1
    tsx: ^4.21.0
    turbo: ^2.6.3
    type-fest: ^5.3.1
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.2.7
    vitest: ~4.0.15
    vue: ^3.5.25
    yaml: ^2.8.2
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
